Name: job_application
Attributes: [first_name, last_name, employee_status, salary]
Proof_Request: [first_name, last_name, phone_number, ssn, degree, status]
Verifiable: {degree: ABC University, status: ABC University, ssn: ABC University}